<a href="https://colab.research.google.com/github/Kevin-anto/tareas-algrebra/blob/main/ExamenTITULOAL_Kevin%20antonio.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Algebra Lineal

### 1er examen parcial

In [1]:
!pip install --target=$nb_path nacal
from nacal import *

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 40.0/40.0 kB 446.1 kB/s eta 0:00:00


EN este notebook deberás realizar cada uno de los ejercicios utilizando Python dentro de los bloques de código, si alguna salida requiere la visualización mediante Latex escribe el bloque correspondiente.

In [4]:
#import math library
import math

1. Genere los vectores $a$ y $ {b}$:

-   el vector ${a}$ está formado por la lista de números: 1, $\frac{1}{3}$, -5, π
-   el vector ${b}$ está formado por la lista de números: 1, $\frac{2}{3}$, 0.01,  $\sqrt 2$
-   súmelos

In [8]:
a= Vector ([1,(fracc(1,3)),-5,math.pi])
b= Vector([1,2/3,0.01,math.sqrt(2)])
print (a+b)

(2, 1.00000000000000, -4.99000000000000, 4.55580621596289,)


2. Proporcione ejemplos de matrices 3 por 3 no nulas de los siguientes
tipos de matrices:

-   Una matriz diagonal



In [9]:
a= Vector([1,0,0])
b= Vector([0,2,0])
c= Vector([0,0,3])
D= Matrix ([a,b,c])
print(D)

|1 0 0|
|0 2 0|
|0 0 3|


-   Una matriz simétrica



In [10]:
a= Vector([1,2,3])
b= Vector([2,4,5])
c= Vector([3,5,6])
D=Matrix([a,b,c])
print(D)

|1 2 3|
|2 4 5|
|3 5 6|


3. Cree la matriz
$${A}=\begin{bmatrix}1&0&0&7\\2&0&7&6\\-4&3&3&5\\0&3&4&-1\end{bmatrix}$$



In [11]:
s= Vector([1,2,-4,0])
e= Vector([0,0,3,3])
f= Vector([0,7,3,4])
r= Vector([7,6,5,-1])
A= Matrix([s,e,f,r])
print(A)

| 1  0  0  7|
| 2  0  7  6|
|-4  3  3  5|
| 0  3  4 -1|


Calcule el siguiente vector: 3 veces la primera columna de $A$
mas la segunda columna de $A$ menos 2 veces la tercera columna
menos 3 veces la última columna de $A$



In [12]:
print(((3*(1|A))+(2|A)-(2*(3|A)-(3*(4|A)))))

(13, 3, 13, 14,)


**4**.Genera la matriz identidad  I de rango 4 y 10


5. Producto punto
Considere los vectores ${x}=(1, 1, -2)$, ${y}=(1, -2, 1)$
calcula el producto punto

In [15]:
x = [1, 1, -2]
y = [1, -2, 1]


producto_punto = sum(a*b for a, b in zip(x, y))

print(producto_punto)

-3


6. Para la siguiente matriz $$\left[ \begin{array}{cccc}3&-2&2\\1&-1&-1\\2&1&2\\ \end{array} \right]$$ lleva a cabo el algoritmo de eliminación paso a paso.

Escribe en una celda separada cada operacion elemental.

In [24]:
a= Vector([3,1,2])
b= Vector([-2,-1,1])
c= Vector([2,-1,2])
D= Matrix([a,b,c])
print(D)

| 3 -2  2|
| 1 -1 -1|
| 2  1  2|


In [33]:
A&T((fracc(1,3),1))

7. Escriba las siguientes matrices elementales de orden 4.


(a) I τ
[(−2)1+3]

(b) I τ
[(0.5)1+4]

(c) I τ
[(-3)2+1]

(d) I τ
[(−10)3]

In [16]:
import numpy as np


In [18]:
I = np.eye(4)

matriz elemental a

In [19]:
E1 = I.copy()
E1[2, 2] = -2
print("Matriz elemental (a):")
print(E1)
print()

Matriz elemental (a):
[[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0. -2.  0.]
 [ 0.  0.  0.  1.]]



matriz elemental b

In [20]:
E2 = I.copy()
E2[3, 3] = 0.5
print("Matriz elemental (b):")
print(E2)
print()

Matriz elemental (b):
[[1.  0.  0.  0. ]
 [0.  1.  0.  0. ]
 [0.  0.  1.  0. ]
 [0.  0.  0.  0.5]]



matriz elemental c

In [21]:
E3 = I.copy()
E3[0, 1] = -3
print("Matriz elemental (c):")
print(E3)
print()

Matriz elemental (c):
[[ 1. -3.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0.  1.]]



matriz elemental d

In [22]:
E4 = I.copy()
E4[2, 2] = -10
print("Matriz elemental (d):")
print(E4)
print()

Matriz elemental (d):
[[  1.   0.   0.   0.]
 [  0.   1.   0.   0.]
 [  0.   0. -10.   0.]
 [  0.   0.   0.   1.]]



8. Realiza el algoritmo de eliminación de Gauss-Jordan para la matriz del ejercicio 6, es decir continua las modificaciones de la matriz mediante operaciones elementales.
Por cada paso del algoritmo escribe la celda de código correspondiente.

9. Encuentra la inversa de la matriz del ejercicio 6.

In [47]:
a= Vector([3,1,2,0,0,0])
b= Vector([-2,-1,1,1,0,0])
c= Vector([2,-1,2,0,1,0])
D= Matrix([a,b,c])
print (D)

| 3 -2  2|
| 1 -1 -1|
| 2  1  2|
| 0  1  0|
| 0  0  1|
| 0  0  0|


10. Resuelva el siguiente sistema de ecuaciones:

$$ \begin{array}{ccc}5x&+7y&-z&=6\\2x&+10y&-2z&=4\\x&+y&+z&=0\\ \end{array} $$

In [35]:
E=Matrix([[5,7,-1],[2,10,-2],[1,1,1]])
print (E)

| 5  7 -1|
| 2 10 -2|
| 1  1  1|


In [37]:
S=Matrix ([[5,7,-1,6],[2,10,-2,4],[1,1,1,0]])
print(S)

| 5  7 -1  6|
| 2 10 -2  4|
| 1  1  1  0|


In [46]:
T((fracc(-1,2) ,2))&S
T((1, 2, 3))&S
T((fracc (- 1, 5),2))&S
T ((4, 2, 3))&S
T((fracc (1, 5) ,1))&S


In [42]:
T((fracc (5, 6) ,3))&S
T((fracc (1, 5) ,3,2))&S
T((fracc (- 1, 3) ,1,2))&S
T((fracc (- 2, 3) ,1,3))&S

In [43]:
T((fracc(15,8),2))&S
T((fracc(-7,5),2,1))&S
T((fracc(14,15),2,3))&S
T((fracc(4,5),3))&S

In [44]:
T((fracc (- 1, 8) ,3,2))&S
T((fracc (3, 8) ,3,1))&S